# Model arguments
model_name_or_path: /home/aiscuser/fhw/model_weights/deepseek-coder-6.7b-base
model_revision: main
torch_dtype: float16
attn_implementation: eager

# Data training arguments
chat_template: "{% if not add_generation_prompt is defined %}\n{% set add_generation_prompt = false %}\n{% endif %}\n{%- set ns = namespace(found=false) -%}\n{%- for message in messages -%}\n    {%- if message['role'] == 'system' -%}\n        {%- set ns.found = true -%}\n    {%- endif -%}\n{%- endfor -%}\n{{bos_token}}{%- if not ns.found -%}\n{{'You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer\\n'}}\n{%- endif %}\n{%- for message in messages %}\n    {%- if message['role'] == 'system' %}\n{{ message['content'] }}\n    {%- else %}\n        {%- if message['role'] == 'user' %}\n{{'### Instruction:\\n' + message['content'] + '\\n'}}\n        {%- else %}\n{{'### Response:\\n' + message['content'] + '\\n<|EOT|>\\n'}}\n        {%- endif %}\n    {%- endif %}\n{%- endfor %}\n{% if add_generation_prompt %}\n{{'### Response:'}}\n{% endif %}"
dataset_mixer:
  data/my: 1.0
dataset_splits:
- train
preprocessing_num_workers: 128

# SFT trainer config
bf16: False
do_eval: False
evaluation_strategy: epoch
gradient_accumulation_steps: 16
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 1.0e-05
log_level: info
logging_steps: 1  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
num_train_epochs: 3
output_dir: output/llama_ins_llama_answer
overwrite_output_dir: True
per_device_eval_batch_size: 8
per_device_train_batch_size: 1
push_to_hub: False
remove_unused_columns: True
report_to:
- tensorboard
save_strategy: "epoch"
save_total_limit: 5
seed: 42
warmup_ratio: 0.1