description: Simple PyTorch job on MNIST on AMLK8s

target:

  service: sing
  name: GenAI-Shared-UKSouth
  workspace_name: Singularity-GenAI-WS-UKSouth

environment:
  image: amlt-sing/acpt-2.2.2-py3.10-cuda12.1
  setup:
    - pip uninstall -y onnxruntime_training
    - python -m pip install .
    - python -m pip install flash-attn --no-build-isolation
code:
   local_dir: $CONFIG_DIR

storage:
  output:
    storage_account_name: aimsfrontierresearcheu01
    container_name: msra
    mount_dir: /blob

# list of jobs to run, we run 2 jobs in this example; High
jobs:
- name: sft_train_alpaca
  sku: 1x80G8
  process_count_per_node: 1
  priority: High
  sla_tier: Standard
  command:
  - printenv | grep -i rank

# # sample 2k
  - CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero3.yaml scripts/run_sft_alpaca.py recipes/zephyr-7b-beta/sft/config_fhwalpaca.yaml